name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  test:
    name: CI
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./smart-contract
    steps:

      # ======== Setup =========

      - name: Checkout project
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install packages
        run: npm install

      # ======== Unit tests =========

      - name: Run Unit Tests
        run: npm run test-json

      - name: Generate Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Unit Tests Results
          path: ${{ github.workspace }}/smart-contract/test-results.json
          reporter: mocha-json

      # ======= Code coverage =======

      - name: Run Test Coverage
        run: npm run coverage

      - name: Generate Coverage Report
        uses: codecov/codecov-action@v3

      # ======== Static analysis =========

      - name: Run Static Analysis
        uses: crytic/slither-action@v0.1.1
        id: slither
        continue-on-error: true
        with:
          target: smart-contract/
          sarif: results.sarif
          fail-on: none

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ steps.slither.outputs.sarif }}

      # ======== Linting =========

      - name: Run Linter
        run: npm run lint
